### ISSUE TITLE
Error when trying to reproduce code in colab

### ISSUE THREAD

**Issue by PradeepSinghMakwana** [epfml/attention-cnn#3] opened 2020-01-25 10:37 UTC
Tried to reproduce the code on Personal Computer without GPU and stuck in thop requirements. Tried with commenting thop, ran part of single epoch, and I have to forcefully stop. Consumed all resources and was too slow without GPU. 

I have re-tried to reproduce the code with GPU in colab. Here are the steps 

1. A fresh installation of anaconda using
```
!wget -c https://repo.continuum.io/archive/Anaconda3-5.1.0-Linux-x86_64.sh
!chmod +x Anaconda3-5.1.0-Linux-x86_64.sh
!bash ./Anaconda3-5.1.0-Linux-x86_64.sh -b -f -p /usr/local
```

2. Install cuda-toolkit with
`!conda install -y --prefix /usr/local pytorch torchvision cudatoolkit=10.0 -c pytorch`

3. Intall requirements (fails with thop) modified file using
```
!mkdir mygit
!git clone https://github.com/epfml/attention-cnn.git mygit
!echo -e "boto3==1.9.234\ntabulate==0.8.3\ntensorboardX==1.8\ntermcolor==1.1.0\n#thop==0.0.31\n" > mygit/requirements.txt
!pip install tqdm
!pip install -r mygit/requirements.txt
```

3. Try running the script. Fails.
`!( cd mygit && bash runs/quadratic/run.sh )`
```
Config overrides:
     optimizer_cosine_lr       -> True (instead of False)
     optimizer_warmup_ratio    -> 0.05 (instead of 0.0)
     batch_size                -> 100 (instead of 300)
     hidden_size               -> 400 (instead of 128)
     num_hidden_layers         -> 6 (instead of 2)
     num_attention_heads       -> 9 (instead of 8)
     attention_isotropic_gaussian -> True (instead of False)
     num_keep_checkpoints      -> 30 (instead of 0)
     output_dir                -> /content/mygit/runs/quadratic (instead of ./output.tmp)
Traceback (most recent call last):
  File "train.py", line 654, in <module>
    main()
  File "train.py", line 116, in main
    store_config()
  File "train.py", line 601, in store_config
    yaml.dump(dict(config), f, sort_keys=False)
  File "/usr/local/lib/python3.6/site-packages/yaml/__init__.py", line 200, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
TypeError: dump_all() got an unexpected keyword argument 'sort_keys'

```
I further changed  File "train.py", line 601, in store_config
    yaml.dump(dict(config), f, sort_keys=False)
to 
    yaml.dump(dict(config), f) # sort_keys removed

Tried to run again. Here is the last error.
```

Config overrides:
     optimizer_cosine_lr       -> True (instead of False)
     optimizer_warmup_ratio    -> 0.05 (instead of 0.0)
     batch_size                -> 100 (instead of 300)
     hidden_size               -> 400 (instead of 128)
     num_hidden_layers         -> 6 (instead of 2)
     num_attention_heads       -> 9 (instead of 8)
     attention_isotropic_gaussian -> True (instead of False)
     num_keep_checkpoints      -> 30 (instead of 0)
     output_dir                -> /content/mygit/runs/quadratic (instead of ./output.tmp)
Tensorboard logs saved in '/content/mygit/runs/quadratic'
Files already downloaded and verified
Files already downloaded and verified
Use DataParallel if multi-GPU
Number of parameters: 12.1M (46.1MiB for float32)
Number of trainable parameters: 12.1M
Epoch 000
Traceback (most recent call last):
  File "train.py", line 654, in <module>
    main()
  File "train.py", line 199, in main
    plot_attention_positions_all_layers(model, 9, writer, epoch)
  File "/content/mygit/utils/plotting.py", line 101, in plot_attention_positions_all_layers
    for layer_idx in range(len(model.encoder.layer)):
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 576, in __getattr__
    type(self).__name__, name))
AttributeError: 'DataParallel' object has no attribute 'encoder'

```

**Comment by jbcdnr** [comment] 2020-01-27 09:20
Thank you for opening this issue and documenting the problem.

Sorry I had disabled multi-GPU to train the models and this clashes with the plotting function. This function is a bit hacky and directly accesses the fields of the `Bert` model. The bug arise because of the `DataParallel` wrapper. I think a quick fix is to comment lines 493 and 494 of `train.py`. Let me know how this goes.

Thank you for trying to reproduce in a Colab notebook, would be valuable :) I did not work in notebooks for this project but maybe it would be better to directly call the `main` method override the `config` dictionary rather than calling the run script.

Have a good week.

**Comment by PradeepSinghMakwana** [comment] 2020-01-28 15:05
Line 493 
Commenting lines to disable DataParallel and benchmark.
#        model = torch.nn.DataParallel(model)
It worked, Thanks. :)

I'm seeing some warnings, does it need attention?
```
Epoch 000
/usr/local/lib/python3.6/site-packages/torch/optim/lr_scheduler.py:122: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)
/usr/local/lib/python3.6/site-packages/torch/optim/lr_scheduler.py:224: UserWarning: To get the last learning rate computed by the scheduler, please use `get_last_lr()`.
  warnings.warn("To get the last learning rate computed by the scheduler, "
 45% 227/500 [04:08<05:15,  1.15s/it]
```

**Comment by jbcdnr** [comment] 2020-01-28 15:55
Yes, I had also this warning after updating PyTorch in the middle of my experimentation. You can discard it :)

I close this issue, don't hesitate to open a new one if you get into trouble!

**Closed by jbcdnr** 2020-01-28 15:55 UTC

**Comment by tntjd7545** [comment] 2020-03-08 12:24
Replacing model.encoder -> model.module.encoder solves 'DataParallel' object has no attribute 'encoder' issue
